import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className={inter.className}>
        <nav
          style={{
            display: "flex",
            gap: "10px",
          }}
        >
          <a href="/">show data</a>
          <a href="/insert">insert </a>
          <a href="/api/createGeneralSheet">الاستاذ العام</a>
          <a href="/api/balance">ميزان المراجة</a>
        </nav>
        <br />
        {children}
      </body>
    </html>
  );
}
